//! Solid.js linting rules

mod components_return_once;
mod consistent_signal_naming;
mod event_handlers;
mod imports;
mod jsx_no_duplicate_props;
mod jsx_no_script_url;
mod jsx_no_undef;
mod jsx_uses_vars;
mod no_array_handlers;
mod no_conditional_signals;
mod no_destructure;
mod no_direct_store_mutation;
mod no_innerhtml;
mod no_proxy_apis;
mod no_react_deps;
mod no_react_specific_props;
mod no_signal_boolean_coercion;
mod no_signal_in_render_body;
mod no_top_level_effects;
mod no_unknown_namespaces;
mod no_unused_signals;
mod prefer_batch;
mod prefer_classlist;
mod prefer_for;
mod prefer_on;
mod prefer_show;
mod reactivity;
mod require_context_default;
mod self_closing_comp;
mod style_prop;

pub use components_return_once::ComponentsReturnOnce;
pub use consistent_signal_naming::ConsistentSignalNaming;
pub use event_handlers::EventHandlers;
pub use imports::Imports;
pub use jsx_no_duplicate_props::JsxNoDuplicateProps;
pub use jsx_no_script_url::JsxNoScriptUrl;
pub use jsx_no_undef::JsxNoUndef;
pub use jsx_uses_vars::JsxUsesVars;
pub use no_array_handlers::NoArrayHandlers;
pub use no_conditional_signals::NoConditionalSignals;
pub use no_destructure::NoDestructure;
pub use no_direct_store_mutation::NoDirectStoreMutation;
pub use no_innerhtml::NoInnerhtml;
pub use no_proxy_apis::NoProxyApis;
pub use no_react_deps::NoReactDeps;
pub use no_react_specific_props::NoReactSpecificProps;
pub use no_signal_boolean_coercion::NoSignalBooleanCoercion;
pub use no_signal_in_render_body::NoSignalInRenderBody;
pub use no_top_level_effects::NoTopLevelEffects;
pub use no_unknown_namespaces::NoUnknownNamespaces;
pub use no_unused_signals::NoUnusedSignals;
pub use prefer_batch::PreferBatch;
pub use prefer_classlist::PreferClasslist;
pub use prefer_for::PreferFor;
pub use prefer_on::PreferOn;
pub use prefer_show::PreferShow;
pub use reactivity::Reactivity;
pub use require_context_default::RequireContextDefault;
pub use self_closing_comp::SelfClosingComp;
pub use style_prop::StyleProp;
