packages:
  - "packages/*"
  - "test"
allowBuilds:
  es5-ext: set this to true or false
  esbuild: set this to true or false
patchedDependencies:
  eslint@8.57.0: patches/eslint@8.57.0.patch
onlyBuiltDependencies:
  - esbuild
  - es5-ext
